/* Generated By:JJTree: Do not edit this line. ASTPrimaryExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTPrimaryExp extends SimpleNode {
  public ASTPrimaryExp(int id) {
    super(id);
  }

  public ASTPrimaryExp(Ice9Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Ice9ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ba1c51985a9cda01ed11bf58efbd1af7 (do not edit this line) */
