/* Generated By:JavaCC: Do not edit this line. Ice9ParserVisitor.java Version 5.0 */
package parser;

public interface Ice9ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTtokenTest node, Object data);
  public Object visit(ASTtypeid node, Object data);
  public Object visit(ASTop node, Object data);
  public Object visit(ASTidlist node, Object data);
  public Object visit(ASTstms node, Object data);
  public Object visit(ASTstm node, Object data);
  public Object visit(ASTotherstm node, Object data);
  public Object visit(ASTreturn_stm node, Object data);
  public Object visit(ASTexit_stm node, Object data);
  public Object visit(ASTbreak_stm node, Object data);
  public Object visit(ASTwrite_stm node, Object data);
  public Object visit(ASTifstm node, Object data);
  public Object visit(ASTdostm node, Object data);
  public Object visit(ASTfa node, Object data);
  public Object visit(ASTproc node, Object data);
  public Object visit(ASTvarlist node, Object data);
  public Object visit(ASTvar node, Object data);
  public Object visit(ASTdeclist node, Object data);
  public Object visit(ASTforward node, Object data);
  public Object visit(ASTtype node, Object data);
  public Object visit(ASTlvalue node, Object data);
  public Object visit(ASTcompareOp node, Object data);
  public Object visit(ASTAdditive node, Object data);
  public Object visit(ASTplusMinus node, Object data);
  public Object visit(ASTTimes node, Object data);
  public Object visit(ASTtimeDivide node, Object data);
  public Object visit(ASTPrefixExp node, Object data);
  public Object visit(ASTUnary node, Object data);
  public Object visit(ASTPrimaryExp node, Object data);
  public Object visit(ASTintTerm node, Object data);
  public Object visit(ASTboolTerm node, Object data);
  public Object visit(ASTreadTerm node, Object data);
  public Object visit(ASTstringTerm node, Object data);
  public Object visit(ASTprocedureCall node, Object data);
  public Object visit(ASTassociateExp node, Object data);
  public Object visit(ASTexp node, Object data);
  public Object visit(ASTnoAssignExp node, Object data);
  public Object visit(ASTcompares node, Object data);
}
/* JavaCC - OriginalChecksum=67e71af78928d2c72285bdf0f96e0b29 (do not edit this line) */
