#! /bin/bash

for num in `seq 1 155`; do
	echo $num
	
#	tr -d '\15' < tests/test$num.9 > unix-tests/test$num.9

	./ice9 generated/test$num.tm < tests/test$num.9
	sed s/[0-9]*:/:/ < generated/test$num.tm > generated/test$num.tm1
	diff -w generated/test$num.tm1 expected/test$num.tm1
	
	./tm10000 -b generated/test$num.tm > out/test$num.out
	diff out/test$num.out expected/test$num.out
	
done

for num in `seq 250 257`; do
	echo $num
	
#	tr -d '\15' < tests/test$num.9 > unix-tests/test$num.9

	./ice9 generated/test$num.tm < tests/test$num.9
	sed s/[0-9]*:/:/ < generated/test$num.tm > generated/test$num.tm1
	diff -w generated/test$num.tm1 expected/test$num.tm1
	
	./tm10000 -b -a 10000000000 generated/test$num.tm > out/test$num.out < tests/input$num.txt
	diff out/test$num.out expected/test$num.out
	
done

for num in `seq 300 307`; do
	echo $num
	
#	tr -d '\15' < tests/test$num.9 > unix-tests/test$num.9

	./ice9 generated/test$num.tm < tests/test$num.9
	sed s/[0-9]*:/:/ < generated/test$num.tm > generated/test$num.tm1
	diff -w generated/test$num.tm1 expected/test$num.tm1
	
	
done

./tm1000 -b generated/test300.tm > out/test300.out
./tm1000 -b generated/test301.tm > out/test301.out
./tm1000 -b generated/test302.tm > out/test302.out
./tm1000 -b generated/test303.tm > out/test303.out
./tm1000 -b generated/test304.tm > out/test304.out
./tm99 -b generated/test305.tm > out/test305.out
./tm96 -b generated/test306.tm > out/test306.out
./tm99 -b generated/test307.tm > out/test307.out

for num in `seq 300 307`; do
	echo $num
	
	diff out/test$num.out expected/test$num.out

done