/* Generated By:JJTree: Do not edit this line. ASTprocedureCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTprocedureCall extends SimpleNode {
  public ASTprocedureCall(int id) {
    super(id);
  }

  public ASTprocedureCall(Ice9Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Ice9ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=39d160a5d2987e81ba45a281e4d6b95b (do not edit this line) */
