/* Generated By:JJTree: Do not edit this line. ASTPrefixExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTPrefixExp extends SimpleNode {
  public ASTPrefixExp(int id) {
    super(id);
  }

  public ASTPrefixExp(Ice9Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Ice9ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=685a40eb6478ff326a80726a01959f18 (do not edit this line) */
