INSERT INTO PRODUCT VALUES ('A', 1001, 'PC');
INSERT INTO PRODUCT VALUES ('A', 1002, 'PC');
INSERT INTO PRODUCT VALUES ('A', 1003, 'PC');
INSERT INTO PRODUCT VALUES ('A', 2004, 'Laptop');
INSERT INTO PRODUCT VALUES ('A', 2005, 'Laptop');
INSERT INTO PRODUCT VALUES ('A', 2006, 'Laptop');
INSERT INTO PRODUCT VALUES ('B', 1004, 'PC');
INSERT INTO PRODUCT VALUES ('B', 1005, 'PC');
INSERT INTO PRODUCT VALUES ('B', 1006, 'PC');
INSERT INTO PRODUCT VALUES ('B', 2007, 'Laptop');
INSERT INTO PRODUCT VALUES ('C', 1007, 'PC');
INSERT INTO PRODUCT VALUES ('D', 1008, 'PC');
INSERT INTO PRODUCT VALUES ('D', 1009, 'PC');
INSERT INTO PRODUCT VALUES ('D', 1010, 'PC');
INSERT INTO PRODUCT VALUES ('D', 3004, 'Printer');
INSERT INTO PRODUCT VALUES ('D', 3005, 'Printer');
INSERT INTO PRODUCT VALUES ('E', 1011, 'PC');
INSERT INTO PRODUCT VALUES ('E', 1012, 'PC');
INSERT INTO PRODUCT VALUES ('E', 1013, 'PC');
INSERT INTO PRODUCT VALUES ('E', 2001, 'Laptop');
INSERT INTO PRODUCT VALUES ('E', 2002, 'Laptop');
INSERT INTO PRODUCT VALUES ('E', 2003, 'Laptop');
INSERT INTO PRODUCT VALUES ('E', 3001, 'Printer');
INSERT INTO PRODUCT VALUES ('E', 3002, 'Printer');
INSERT INTO PRODUCT VALUES ('E', 3003, 'Printer');
INSERT INTO PRODUCT VALUES ('F', 2008, 'Laptop');
INSERT INTO PRODUCT VALUES ('F', 2009, 'Laptop');
INSERT INTO PRODUCT VALUES ('G', 2010, 'Laptop');
INSERT INTO PRODUCT VALUES ('H', 3006, 'Printer');
INSERT INTO PRODUCT VALUES ('H', 3007, 'Printer');



