package parser;
/* Generated By:JJTree: Do not edit this line. ASTAdditive.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTAdditive extends SimpleNode {
  public ASTAdditive(int id) {
    super(id);
  }

  public ASTAdditive(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5098c267d570e38f99ee86dddaea8ccb (do not edit this line) */
