/* Generated By:JJTree: Do not edit this line. ASTbreak_stm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ASTbreak_stm extends SimpleNode {
  public ASTbreak_stm(int id) {
    super(id);
  }

  public ASTbreak_stm(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0baf55034e498babc182d8ae2b65839e (do not edit this line) */
