package parser;
/* Generated By:JJTree: Do not edit this line. ASTidlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTidlist extends SimpleNode {
  public ASTidlist(int id) {
    super(id);
  }

  public ASTidlist(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=285879a2930869423b8cdc658b6c1155 (do not edit this line) */
