package parser;
/* Generated By:JJTree: Do not edit this line. ASTifstm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTifstm extends SimpleNode {
  public ASTifstm(int id) {
    super(id);
  }

  public ASTifstm(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7fb80ab42f5e14f932c2b9d568a11b67 (do not edit this line) */
