package parser;
/* Generated By:JJTree: Do not edit this line. ASTlvalue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTlvalue extends SimpleNode {
  public ASTlvalue(int id) {
    super(id);
  }

  public ASTlvalue(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0985f806decdbd4b9360419cc5d0a2a3 (do not edit this line) */
