/* Generated By:JJTree: Do not edit this line. ASTreturn_stm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ASTreturn_stm extends SimpleNode {
  public ASTreturn_stm(int id) {
    super(id);
  }

  public ASTreturn_stm(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f32ddc9e7e5aab24ce5b4460137ebdd9 (do not edit this line) */
