package parser;
/* Generated By:JJTree: Do not edit this line. ASTstms.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTstms extends SimpleNode {
  public ASTstms(int id) {
    super(id);
  }

  public ASTstms(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9550cbe71ce649ee4469e0888bfcaa7b (do not edit this line) */
