package parser;
/* Generated By:JJTree: Do not edit this line. ASTtimeDivide.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTtimeDivide extends SimpleNode {
  public ASTtimeDivide(int id) {
    super(id);
  }

  public ASTtimeDivide(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df79ec41574acaa595ffeac5de2d4e64 (do not edit this line) */
