/* Generated By:JJTree: Do not edit this line. ASTwrite_stm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ASTwrite_stm extends SimpleNode {
  public ASTwrite_stm(int id) {
    super(id);
  }

  public ASTwrite_stm(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d6b7a6d6bf690f21a45d997cc8e7900 (do not edit this line) */
