/* Generated By:JJTree: Do not edit this line. ASTnoAssignExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTnoAssignExp extends SimpleNode {
  public ASTnoAssignExp(int id) {
    super(id);
  }

  public ASTnoAssignExp(Ice9Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Ice9ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=33a7f57d2ff1fe1502c4691a3d488eb5 (do not edit this line) */
