/* Generated By:JJTree: Do not edit this line. ASTwrite_stm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTwrite_stm extends SimpleNode {
  public ASTwrite_stm(int id) {
    super(id);
  }

  public ASTwrite_stm(Ice9Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Ice9ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=98beecc024d7a6aeafa57a1e55ed6e3a (do not edit this line) */
