/* Generated By:JavaCC: Do not edit this line. Ice9ParserTreeConstants.java Version 5.0 */
package parser;

public interface Ice9ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTTOKENTEST = 1;
  public int JJTTYPEID = 2;
  public int JJTOP = 3;
  public int JJTIDLIST = 4;
  public int JJTSTMS = 5;
  public int JJTSTM = 6;
  public int JJTOTHERSTM = 7;
  public int JJTRETURN_STM = 8;
  public int JJTEXIT_STM = 9;
  public int JJTBREAK_STM = 10;
  public int JJTWRITE_STM = 11;
  public int JJTIFSTM = 12;
  public int JJTDOSTM = 13;
  public int JJTFA = 14;
  public int JJTPROC = 15;
  public int JJTVARLIST = 16;
  public int JJTVAR = 17;
  public int JJTDECLIST = 18;
  public int JJTFORWARD = 19;
  public int JJTTYPE = 20;
  public int JJTLVALUE = 21;
  public int JJTCOMPAREOP = 22;
  public int JJTADDITIVE = 23;
  public int JJTPLUSMINUS = 24;
  public int JJTTIMES = 25;
  public int JJTTIMEDIVIDE = 26;
  public int JJTPREFIXEXP = 27;
  public int JJTUNARY = 28;
  public int JJTPRIMARYEXP = 29;
  public int JJTINTTERM = 30;
  public int JJTBOOLTERM = 31;
  public int JJTREADTERM = 32;
  public int JJTSTRINGTERM = 33;
  public int JJTPROCEDURECALL = 34;
  public int JJTASSOCIATEEXP = 35;
  public int JJTEXP = 36;
  public int JJTASSIGNEXP = 37;
  public int JJTNOASSIGNEXP = 38;
  public int JJTCOMPARES = 39;


  public String[] jjtNodeName = {
    "program",
    "tokenTest",
    "typeid",
    "op",
    "idlist",
    "stms",
    "stm",
    "otherstm",
    "return_stm",
    "exit_stm",
    "break_stm",
    "write_stm",
    "ifstm",
    "dostm",
    "fa",
    "proc",
    "varlist",
    "var",
    "declist",
    "forward",
    "type",
    "lvalue",
    "compareOp",
    "Additive",
    "plusMinus",
    "Times",
    "timeDivide",
    "PrefixExp",
    "Unary",
    "PrimaryExp",
    "intTerm",
    "boolTerm",
    "readTerm",
    "stringTerm",
    "procedureCall",
    "associateExp",
    "exp",
    "assignExp",
    "noAssignExp",
    "compares",
  };
}
/* JavaCC - OriginalChecksum=8bde2274078d4d8afa44c1ec0e48f12e (do not edit this line) */
