/* Generated By:JJTree: Do not edit this line. ASTbreak_stm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTbreak_stm extends SimpleNode {
  public ASTbreak_stm(int id) {
    super(id);
  }

  public ASTbreak_stm(Ice9Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Ice9ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6edba87fa05fe75a6121badc62201f6d (do not edit this line) */
