/* Generated By:JJTree: Do not edit this line. ASTassigns.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ASTassigns extends SimpleNode {
  public ASTassigns(int id) {
    super(id);
  }

  public ASTassigns(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1a210e49c1aada7c84bb4af0c538e78 (do not edit this line) */
