package parser;
/* Generated By:JJTree: Do not edit this line. ASTassociateExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTassociateExp extends SimpleNode {
  public ASTassociateExp(int id) {
    super(id);
  }

  public ASTassociateExp(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9e46aa4f94e82139f4cbb5a1f27596d (do not edit this line) */
