package parser;
/* Generated By:JJTree: Do not edit this line. ASTcompareOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTcompareOp extends SimpleNode {
  public ASTcompareOp(int id) {
    super(id);
  }

  public ASTcompareOp(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc93ccdc7ad18a41447431ebc6ca4372 (do not edit this line) */
