package parser;
/* Generated By:JJTree: Do not edit this line. ASTcompares.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTcompares extends SimpleNode {
  public ASTcompares(int id) {
    super(id);
  }

  public ASTcompares(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=846675b9a038bbff23686af9249e1b42 (do not edit this line) */
