package parser;
/* Generated By:JJTree: Do not edit this line. ASTdeclist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTdeclist extends SimpleNode {
  public ASTdeclist(int id) {
    super(id);
  }

  public ASTdeclist(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b3199f1f9636bdfc30fb4612a448d90 (do not edit this line) */
