package parser;
/* Generated By:JJTree: Do not edit this line. ASTexp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTexp extends SimpleNode {
  public ASTexp(int id) {
    super(id);
  }

  public ASTexp(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c57a0552c332d9a33cd32ca960a71719 (do not edit this line) */
