package parser;
/* Generated By:JJTree: Do not edit this line. ASTforward.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTforward extends SimpleNode {
  public ASTforward(int id) {
    super(id);
  }

  public ASTforward(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5eb2d4aaed31dc00e84ba8ae61c1b9a9 (do not edit this line) */
