package parser;
/* Generated By:JJTree: Do not edit this line. ASTnoAssignExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTnoAssignExp extends SimpleNode {
  public ASTnoAssignExp(int id) {
    super(id);
  }

  public ASTnoAssignExp(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7bd84f01bab817a732763c9cfb4e5d0b (do not edit this line) */
