package parser;
/* Generated By:JJTree: Do not edit this line. ASTop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTop extends SimpleNode {
  public ASTop(int id) {
    super(id);
  }

  public ASTop(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29dbf5a7c6fa44742a5273f6dd5469e0 (do not edit this line) */
