package parser;
/* Generated By:JJTree: Do not edit this line. ASTotherstm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTotherstm extends SimpleNode {
  public ASTotherstm(int id) {
    super(id);
  }

  public ASTotherstm(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eee25869bc4023ba6ac0715c75b812d0 (do not edit this line) */
