package parser;
/* Generated By:JJTree: Do not edit this line. ASTplusMinus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTplusMinus extends SimpleNode {
  public ASTplusMinus(int id) {
    super(id);
  }

  public ASTplusMinus(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=18a867f1c277bb61e3d1b77dd96c8d1d (do not edit this line) */
