package parser;
/* Generated By:JJTree: Do not edit this line. ASTprocedureCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTprocedureCall extends SimpleNode {
  public ASTprocedureCall(int id) {
    super(id);
  }

  public ASTprocedureCall(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5ae067b95ef17e87329faa51941c2493 (do not edit this line) */
