package parser;
/* Generated By:JJTree: Do not edit this line. ASTPrefixExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTPrefixExp extends SimpleNode {
  public ASTPrefixExp(int id) {
    super(id);
  }

  public ASTPrefixExp(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=682fdcf1cae30c6e96270815e1dee9bd (do not edit this line) */
