package parser;
/* Generated By:JJTree: Do not edit this line. ASTPrimaryExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTPrimaryExp extends SimpleNode {
  public ASTPrimaryExp(int id) {
    super(id);
  }

  public ASTPrimaryExp(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e295788e3ef1a21579632b6ecac199b1 (do not edit this line) */
