package parser;
/* Generated By:JJTree: Do not edit this line. ASTstm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTstm extends SimpleNode {
  public ASTstm(int id) {
    super(id);
  }

  public ASTstm(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a07c61c2c2397b7e2c19d5a8e23b2f3 (do not edit this line) */
