package parser;
/* Generated By:JJTree: Do not edit this line. ASTtypeid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTtypeid extends SimpleNode {
  public ASTtypeid(int id) {
    super(id);
  }

  public ASTtypeid(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=703dc0ac60d55fb880aa5df8aee34675 (do not edit this line) */
