package parser;
/* Generated By:JJTree: Do not edit this line. ASTtokenTest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTtokenTest extends SimpleNode {
  public ASTtokenTest(int id) {
    super(id);
  }

  public ASTtokenTest(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e9e3dfdd737cc045aa4891da2a5ed93 (do not edit this line) */
