package parser;
/* Generated By:JJTree: Do not edit this line. ASTUnary.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTUnary extends SimpleNode {
  public ASTUnary(int id) {
    super(id);
  }

  public ASTUnary(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=28622c9f96160bba4c39ac730cd99dbf (do not edit this line) */
