package parser;
/* Generated By:JJTree: Do not edit this line. ASTvarlist.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
@SuppressWarnings("all")
class ASTvarlist extends SimpleNode {
  public ASTvarlist(int id) {
    super(id);
  }

  public ASTvarlist(Ice9Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43984422c1b8be971a94d4dfad2b0756 (do not edit this line) */
