/* Generated By:JavaCC: Do not edit this line. Ice9ParserTreeConstants.java Version 5.0 */
package parser;

@SuppressWarnings("all")
public interface Ice9ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTTOKENTEST = 1;
  public int JJTTYPEID = 2;
  public int JJTOP = 3;
  public int JJTIDLIST = 4;
  public int JJTSTMS = 5;
  public int JJTSTM = 6;
  public int JJTOTHERSTM = 7;
  public int JJTRETURN_STM = 8;
  public int JJTEXIT_STM = 9;
  public int JJTBREAK_STM = 10;
  public int JJTWRITE_STM = 11;
  public int JJTIFSTM = 12;
  public int JJTDOSTM = 13;
  public int JJTFA = 14;
  public int JJTPROC = 15;
  public int JJTVARLIST = 16;
  public int JJTVAR = 17;
  public int JJTDECLIST = 18;
  public int JJTFORWARD = 19;
  public int JJTTYPE = 20;
  public int JJTLVALUE = 21;
  public int JJTCOMPAREOP = 22;
  public int JJTADDITIVE = 23;
  public int JJTPLUSMINUS = 24;
  public int JJTTIMES = 25;
  public int JJTTIMEDIVIDE = 26;
  public int JJTPREFIXEXP = 27;
  public int JJTUNARY = 28;
  public int JJTPRIMARYEXP = 29;
  public int JJTPROCEDURECALL = 30;
  public int JJTASSOCIATEEXP = 31;
  public int JJTEXP = 32;
  public int JJTNOASSIGNEXP = 33;
  public int JJTCOMPARES = 34;


  public String[] jjtNodeName = {
    "program",
    "tokenTest",
    "typeid",
    "op",
    "idlist",
    "stms",
    "stm",
    "otherstm",
    "return_stm",
    "exit_stm",
    "break_stm",
    "write_stm",
    "ifstm",
    "dostm",
    "fa",
    "proc",
    "varlist",
    "var",
    "declist",
    "forward",
    "type",
    "lvalue",
    "compareOp",
    "Additive",
    "plusMinus",
    "Times",
    "timeDivide",
    "PrefixExp",
    "Unary",
    "PrimaryExp",
    "procedureCall",
    "associateExp",
    "exp",
    "noAssignExp",
    "compares",
  };
}
/* JavaCC - OriginalChecksum=b36a8e3039b39c00ad7624df9aa23e4c (do not edit this line) */
